### ISSUE TITLE
Rendering of the bottom row of the vertical warp background keeps flatlining

### ISSUE THREAD

**Issue by InfoTeddy** [Colon-D/VVVVVV-over-30-FPS#1]
This is how the bottom row of a vertical warp background looks in the original game:
![this_is_how_warp_backgrounds_work](https://user-images.githubusercontent.com/59748578/72764420-e4ee9780-3b9c-11ea-9c08-720b861627cc.png)

This is how the bottom row of a vertical warp background looks in this over-30-FPS mod:
![thats_not_how_warp_background_works](https://user-images.githubusercontent.com/59748578/72764307-6134ab00-3b9c-11ea-9df5-7b93304474d7.png)

The difference being that, for some reason in this mod, the bottom row seems to "flatline" and be a duplicate row of pixels of the warp background tiles, instead of being another copy of the warp background tiles.

Note that in the main game, the bottom row of the vertical warp background is always covered by a roomname. However, that is not necessarily so in custom levels, such as this one.

**Comment by Colon-D** [comment]
This has been fixed.

In the original game this background works by:
Setting up a surface to draw to
Drawing 15 rows (only once) to the surface
Drawing the 16th row to the surface (this happens every frame)
Moving the drawing on the surface up (this happens every frame)

In the modded game this worked by:
Drawing 15 rows (every frame) to the surface

This is less efficient but easier for me to work with.

I have now increased the number of rows drawn every frame to 16 rows.
