### ISSUE TITLE
You cannot edge-flip off of a vertical moving platform

### ISSUE THREAD

**Issue by InfoTeddy** [Colon-D/VVVVVV-over-30-FPS#5]
Edge-flipping is when you flip off of a surface after leaving it. In the original game, you get to flip off of a surface up to at most 2 frames from leaving it, and as for vertical moving platforms, in most circumstances you only get 1 frame to edge-flip off of them. (All frames mentioned are at 30 FPS, i.e. 1000/34 FPS.)

This mod preserves the edge-flipping off of solid surface tiles, but it does _not_ preserve the 1 frame you get to edge-flip off of a moving vertical platform.

The reason that this is an issue is because as a result of being unable to edge-flip off of a vertical moving platform, one of my TASes for Dimension Open desyncs as a result. At one point in the TAS, Viridian edge-flips off of a vertical moving platform, but in this mod they cannot, and as a result the TAS desyncs.

Pretty impressive though, the desync is only 1 minute and 55 seconds in to the TAS. I'm impressed that the TAS managed to last that long through the mod without desyncing.

**Comment by Colon-D** [comment]
The variables involved with determining whether the player is on the ground or on the roof are:
set to 2 when colliding with the floor/roof inside of the fixed render function
decremented in the fixed render function
set to true (1) when colliding with the floor/roof of a moving platform in the gamelogic function.

In my mod, the order of these functions is:
gamelogic
gamerenderfixed

This is opposite of the original game, and was done to solve some visual glitches, but I was afraid that this would cause some issues, and this appears to be one of them, there might be more issues like this which I have not found, but hopefully not.

I have now split the gamerenderfixed function into two, gamerenderfixedpre, and gamerenderfixedpost.

The new order is:
gamerenderfixedpre
gamelogic
gamerenderfixedpost

The code related to setting and decrementing the the onground and onroof variables are now done before the gamelogic is processed, which should hopefully solve this.

All the above also applies to the towerrenderfixed function.
